// ============================================================================
// Content for the static info pages (About / How it works / Privacy / Terms).
// EASY TO EDIT — all copy lives here, not deep in JSX. Privacy + Terms are
// legal-review DRAFTS (draft:true) and WILL be replaced after legal review:
// swap the blocks below and flip `draft` / set `updated` when finalized.
//
// {SITE_NAME} comes from the single config constant (still parked) via DISPLAY_NAME.
// Inline markup in text: **bold** and [label](href). Block helpers: h()=subhead, p()=paragraph, ul()=list.
// Display only — no model/prediction/data. Project: ahcfrgxczbgdvrqmbisw
// ============================================================================
import { SITE_NAME, COMPANY, COMPANY_URL, CONTACT_EMAIL } from "../config";

// Product label for prose/headings — falls back to the company name while the name is parked.
export const DISPLAY_NAME = SITE_NAME || COMPANY;

// "Last updated" for the legal pages — settable fields (parked until published).
export const PRIVACY_UPDATED = "June 7, 2026";
export const TERMS_UPDATED = "June 7, 2026";

const h = (text) => ({ type: "h", text });
const p = (text) => ({ type: "p", text });
const ul = (items) => ({ type: "ul", items });

export const PAGE_ORDER = ["about", "how", "privacy", "terms"];

export const PAGES = {
  about: {
    navLabel: "About",
    title: `About ${DISPLAY_NAME}`,
    blocks: [
      p(`${DISPLAY_NAME} is a World Cup 2026 match-prediction project built by **${COMPANY}**, a Vancouver-based AI studio. The expanded 48-team, three-nation 2026 tournament is the most complex World Cup ever — 104 matches, intricate group-advancement and third-place tiebreaker rules, and knockout paths that shift with every result. We built ${DISPLAY_NAME} as a way to make that complexity legible: to forecast how the tournament might unfold, and to show what becomes possible when a rigorous statistical model and modern AI work together rather than one pretending to be the other.`),
      p(`It's also a showcase. ${COMPANY} helps businesses bridge established operational know-how with AI-native delivery — AI consulting, AI agents, web development, and digital marketing. ${DISPLAY_NAME} demonstrates that philosophy on a hard, public problem: a transparent prediction engine where the math does the forecasting and the AI does the explaining, each shown on its own terms.`),
      p(`Learn more about ${COMPANY} at [mostailabs.com](${COMPANY_URL}).`),
    ],
  },

  how: {
    navLabel: "How it works",
    title: `How ${DISPLAY_NAME} works`,
    blocks: [
      h("The short version"),
      p("Our predictions come from a statistical football model, not from AI guessing."),
      p("The pre-tournament estimate is built from **7,871 historical international matches** and **20,000 calculated tournament simulations**. As real World Cup results come in, the numbers update to reflect what has actually happened."),
      p("The model uses real match data, team strength ratings, recent form, and tournament rules to calculate each team's chances. A separate AI layer then explains those numbers in simple language."),
      p("We keep the two parts separate: **the math calculates the forecast. The AI explains the story.**"),
      p("The AI does not invent the probabilities. It only explains the numbers produced by the prediction system."),
      h("The prediction model"),
      p("At the core is a football rating system, similar to the kind of rating method used in chess and many professional sports."),
      p("Each team has a strength rating based on thousands of real international matches. The system looks at things like:"),
      ul([
        "Past results",
        "Opponent strength",
        "Recent form",
        "Team performance over time",
        "Match context",
      ]),
      p("For each game, the model compares the two teams and calculates the chance of each result:"),
      ul([
        "Team A wins",
        "Draw",
        "Team B wins",
      ]),
      p("Football is different from many sports because draws are common, especially when teams are evenly matched. So the model includes a football-specific adjustment for that."),
      h("From one match to the whole tournament"),
      p("Predicting one match is only part of the story."),
      p("To estimate tournament outcomes, the system runs thousands of possible versions of the World Cup using standard mathematical calculations."),
      p('Think of it like asking: **"What could happen if this tournament was played many different times?"**'),
      p("In each version, the system plays every group match, applies FIFA's tournament rules, works out who advances, builds the knockout bracket, and continues through to the final."),
      p("After thousands of these calculations, we count how often each team:"),
      ul([
        "Wins its group",
        "Finishes second",
        "Advances as one of the best third-place teams",
        "Reaches the knockout stage",
        "Goes deeper into the tournament",
      ]),
      p("That is where the percentages come from."),
      p("So if a team has a 64% chance to reach the knockout stage, it means that across thousands of calculated tournament scenarios, that team advanced in about 64% of them."),
      h("Working out what your team needs"),
      p("The new 48-team World Cup format is much harder to follow than older tournaments."),
      p("It is not just the top two teams from each group. The eight best third-place teams also qualify, and those teams are decided across all twelve groups together."),
      p("That can make the group stage confusing."),
      p("Our system watches the whole tournament table at once and works out what each team needs. For example:"),
      ul([
        "Already qualified",
        "Already eliminated",
        "Needs a win",
        "A draw might be enough",
        "Needs to win by a certain goal difference",
        "Needs help from results in other groups",
      ]),
      p("This is hard to calculate by eye, especially while multiple groups are still playing. The engine does that work automatically."),
      p("As more real matches are played, the picture becomes clearer. Early in the tournament, the system shows possible scenarios. Later, it becomes much more specific."),
      h("Who your team could play next"),
      p("Once the group stage is finished, the uncertainty is gone."),
      p("At that point, the system no longer needs to estimate who might qualify. It uses the official FIFA bracket rules to show each team's confirmed Round-of-32 opponent."),
      p("Until then, it can show the most likely opponent paths based on the current standings and remaining matches."),
      h("The numbers update during the tournament"),
      p("Before the tournament begins, the predictions are based on historical results, team strength, recent form, and tournament structure."),
      p("As real matches happen, the system updates - but it is worth being precise about how, because we would rather be accurate than just sound impressive."),
      p("During the group stage, each real result gets locked into the picture. The system stops estimating that match and treats it as fact. Then it recalculates everything that depends on it:"),
      ul([
        "Who is on course to advance",
        "Which teams are still alive",
        "Which teams are already out",
        "How the third-place race looks",
        "What each team's possible route could be",
      ]),
      p("The team strength ratings themselves stay as they were before the tournament. What changes is that more and more of the tournament is now known instead of estimated."),
      p("So the qualification picture sharpens with every game:"),
      ul([
        "Before the tournament, the model works entirely from estimates.",
        "After one group game, one real result is locked in.",
        "After two group games, the qualification picture is much clearer.",
        "After the group stage, every group place is settled - nothing about who advances is estimated anymore.",
      ]),
      p("Once the group stage finishes, the knockout bracket is real, not estimated. We know exactly which teams are in it and who they will play."),
      p("At that point, the forecast for the knockout rounds can also take into account how teams actually performed in their group games, not just their pre-tournament form. So the deeper-round predictions reflect the tournament as it has actually unfolded."),
      p("The forecast gets more reliable as real results replace pre-tournament assumptions."),
      h("What the AI does"),
      p("The AI does not decide who wins."),
      p("The AI reads the model's numbers and turns them into clear explanations."),
      p("It helps explain things like:"),
      ul([
        "Why a team's chance increased or dropped",
        "What a result means for the group",
        "What a team needs to qualify",
        "Which opponent they may face next",
        "How squad strength, form, venue, or weather might affect the story",
      ]),
      p("The AI is given the model's numbers. It does not create them."),
      p("Every probability shown in the app comes from the prediction system or verified data, not from AI imagination."),
      h("What the AI does not do"),
      p("The AI does not:"),
      ul([
        "Invent match probabilities",
        "Create betting odds",
        "Guarantee results",
        "Replace the statistical model",
        "Pretend to know things that have not happened yet",
      ]),
      p("Its job is to make the numbers easier to understand."),
      h("Honest about the limits"),
      p("These predictions are estimates, not guarantees."),
      p("A 73% chance does not mean a team will definitely win. It means the model sees that team as the stronger possibility based on the available data."),
      p("Football is unpredictable. A red card, injury, bad weather, tactical change, penalty, referee decision, or one great moment can change everything."),
      p("The model understands historical results and team strength. It does not know the future."),
      p("That is why we show probabilities instead of certainties."),
      h("Not betting advice"),
      p("These predictions are for information, analysis, and entertainment."),
      p("They are not betting odds, gambling advice, or a recommendation to place a wager."),
      p("We do not run betting services, and we do not encourage gambling."),
      h("Small chances still matter"),
      p("Some teams will have a small chance of going far, but we do not hide those numbers."),
      p("Every team that qualified has a path through the tournament. Some paths are wide. Some are very narrow. The app shows that honestly."),
      p("An underdog may only have a small percentage chance, but small does not mean impossible."),
      p("That is part of what makes football exciting."),
      h("The data behind it"),
      p("The system uses football data, historical international results, team ratings, player information, tournament rules, venue details, and weather context where available."),
      p("Data sources may include:"),
      ul([
        "API-Football for match and player data",
        "Official FIFA tournament rules and match structure",
        "Historical international football results",
        "Team rating calculations",
        "Weather data from Open-Meteo",
        "Public and official football information where appropriate",
      ]),
      p("We aim to keep the system transparent, clearly separated from betting, and honest about what the numbers can and cannot tell you."),
    ],
  },

  privacy: {
    navLabel: "Privacy",
    title: "Privacy Policy",
    updated: PRIVACY_UPDATED,
    draft: true,
    blocks: [
      p(`${COMPANY} respects your privacy. This Privacy Policy explains what information we collect when you visit [${COMPANY_URL.replace(/^https?:\/\//, "")}](${COMPANY_URL}), contact us, or use our services, and how we use, protect, and share that information.`),
      p("This policy is intended to be clear and practical, but it should be reviewed by a qualified legal professional before publication."),
      h("1. What We Collect"),
      p("We collect limited information depending on how you interact with our website and services."),
      h("Information you provide to us"),
      p("When you contact us through a form, email, phone call, booking link, or other communication channel, we may collect:"),
      ul([
        "Your name",
        "Business name",
        "Email address",
        "Phone number",
        "Website URL",
        "Project details or service interests",
        "Any other information you choose to provide in your message",
      ]),
      p("We do not require visitors to create an account on our website."),
      h("Website and usage data"),
      p("We may collect basic technical and usage information to understand how visitors use our website and to improve performance. This may include:"),
      ul([
        "Pages viewed",
        "Date and time of visit",
        "Device type",
        "Browser type",
        "Approximate region or city",
        "Referring website or search engine",
        "General interaction data, such as clicks or form submissions",
      ]),
      p("Where possible, we use aggregated or anonymized analytics data rather than information that directly identifies you."),
      h("Client and project information"),
      p("If you become a client, we may collect additional information needed to deliver services, such as:"),
      ul([
        "Website access details",
        "Advertising account access",
        "Analytics or Search Console access",
        "CRM, email, or automation platform details",
        "Business goals, marketing data, customer journey information, and project requirements",
      ]),
      p("We only request access that is reasonably needed to provide the agreed services."),
      h("2. How We Use Information"),
      p("We use the information we collect to:"),
      ul([
        "Respond to inquiries",
        "Provide quotes, proposals, and service information",
        "Deliver website, SEO, AI implementation, advertising, consulting, and related services",
        "Improve our website and services",
        "Understand which pages and features are useful to visitors",
        "Communicate with clients about projects, support, updates, and billing",
        "Maintain website security and prevent misuse",
        "Comply with legal, tax, accounting, and business obligations",
      ]),
      p("We do not sell your personal information."),
      h("3. Cookies and Local Storage"),
      p("Our website may use cookies, pixels, local storage, or similar technologies for:"),
      ul([
        "Website functionality",
        "Analytics and performance measurement",
        "Security",
        "Remembering preferences",
        "Marketing or advertising measurement, if enabled",
      ]),
      p("Some third-party tools, such as analytics, advertising, embedded content, or booking tools, may also use cookies or similar technologies."),
      p("If we serve visitors in regions where cookie consent is required, such as the European Union or United Kingdom, we should provide a cookie consent option before non-essential cookies are used."),
      p("You can also control cookies through your browser settings."),
      h("4. Third-Party Services"),
      p("We may use third-party services to operate our website, communicate with visitors, deliver client work, analyze performance, and improve our services."),
      p("These may include services such as:"),
      ul([
        "Website hosting and deployment providers",
        "Domain, DNS, and security providers",
        "Analytics tools",
        "Contact form or booking tools",
        "Email and business communication tools",
        "CRM or project management tools",
        "Payment or invoicing tools",
        "Advertising platforms",
        "AI tools and automation platforms",
        "Data providers or APIs used in client projects",
      ]),
      p("These third parties may process limited technical, contact, or business information only as needed to provide their services to us."),
      p("Where possible, we choose reputable providers and limit the information shared with them."),
      h("5. AI Tools and Automation"),
      p(`${COMPANY} provides AI implementation, automation, and consulting services. In some cases, client-provided information may be processed through AI tools or automation systems to help with tasks such as:`),
      ul([
        "Lead qualification",
        "Customer support workflows",
        "Content drafting",
        "Business process automation",
        "Reporting and analysis",
        "Website or marketing improvements",
      ]),
      p("We do not intentionally submit sensitive personal information to AI tools unless it is necessary for the service, authorized by the client, and appropriate safeguards are in place."),
      p("Clients should avoid sending unnecessary sensitive personal information unless specifically requested for a defined purpose."),
      h("6. Data Retention"),
      p("We keep personal information only as long as reasonably necessary for the purpose it was collected, including:"),
      ul([
        "Responding to inquiries",
        "Providing services",
        "Maintaining business records",
        "Meeting legal, tax, accounting, or contractual obligations",
        "Resolving disputes or enforcing agreements",
      ]),
      p("When information is no longer needed, we will delete, anonymize, or securely archive it where reasonable."),
      h("7. How We Protect Information"),
      p("We use reasonable administrative, technical, and organizational safeguards to protect information against unauthorized access, loss, misuse, or disclosure."),
      p("However, no website, email system, or online service can be guaranteed to be completely secure. You should avoid sending highly sensitive information through ordinary website forms or email unless we have agreed on a secure method."),
      h("8. Your Privacy Rights"),
      p("Depending on where you live, you may have rights regarding your personal information. These may include the right to:"),
      ul([
        "Request access to personal information we hold about you",
        "Request correction of inaccurate information",
        "Request deletion of your information, subject to legal or business retention requirements",
        "Withdraw consent where processing is based on consent",
        "Object to certain uses of your information",
        "Request a copy of your information in a portable format, where applicable",
        "Opt out of certain marketing communications",
      ]),
      p("Canadian privacy laws, including PIPEDA, may apply to our handling of personal information in commercial activities. Visitors from other regions, including the European Union, United Kingdom, or California, may have additional rights under applicable local laws."),
      p(`To make a privacy request, contact us at [${CONTACT_EMAIL}](mailto:${CONTACT_EMAIL}).`),
      p("We may need to verify your identity before responding to a request."),
      h("9. Marketing Communications"),
      p("If you choose to receive emails, updates, or marketing communications from us, you can unsubscribe or ask us to stop contacting you at any time."),
      p("We may still send non-marketing messages related to active projects, transactions, legal notices, or service updates."),
      h("10. Children's Privacy"),
      p("Our website and services are intended for businesses and adults. They are not directed at children under 13."),
      p("We do not knowingly collect personal information from children under 13. If we learn that we have collected information from a child under 13, we will take reasonable steps to delete it."),
      p("If your business serves children or youth and you work with us on a project involving young users, we will discuss additional privacy requirements before collecting or processing related data."),
      h("11. International Visitors"),
      p(`${COMPANY} is based in Canada. If you visit our website or contact us from outside Canada, your information may be processed in Canada or by third-party service providers in other countries.`),
      p("Privacy laws may differ from those in your country. We take reasonable steps to protect information in line with this policy and applicable law."),
      h("12. Links to Other Websites"),
      p("Our website may contain links to third-party websites, platforms, or tools. We are not responsible for the privacy practices, content, or security of those third-party websites."),
      p("You should review their privacy policies before providing personal information."),
      h("13. Changes to This Policy"),
      p("We may update this Privacy Policy from time to time. When we do, we will update the Last updated date at the top of this page."),
      p("Material changes may be communicated more prominently where appropriate."),
      h("14. Contact Us"),
      p(`For privacy questions, requests, or concerns, contact **${COMPANY}** in Vancouver, British Columbia, Canada at [${CONTACT_EMAIL}](mailto:${CONTACT_EMAIL}) or visit [${COMPANY_URL.replace(/^https?:\/\//, "")}](${COMPANY_URL}).`),
    ],
  },

  terms: {
    navLabel: "Terms",
    title: "Terms of Use",
    updated: TERMS_UPDATED,
    draft: true,
    blocks: [
      p(`These Terms of Use govern your access to and use of the ${COMPANY} World Cup prediction app, website, content, tools, reports, simulations, and related services (collectively, the Service).`),
      p("By accessing or using the Service, you agree to these Terms. If you do not agree, do not use the Service."),
      h("1. Who We Are"),
      p(`The Service is operated by **${COMPANY}**, based in Vancouver, British Columbia, Canada.`),
      p(`Contact: [${CONTACT_EMAIL}](mailto:${CONTACT_EMAIL})`),
      h("2. What This Service Is"),
      p(`${COMPANY} provides statistical match predictions, tournament simulations, probability estimates, football data summaries, and AI-generated analysis related to the 2026 World Cup.`),
      p("The Service is provided for **informational, educational, analytical, and entertainment purposes only**."),
      p("The Service may include:"),
      ul([
        "Match predictions",
        "Win/draw/loss probabilities",
        "Group-stage simulations",
        "Tournament advancement probabilities",
        "Team and player analysis",
        "Data-driven commentary",
        "AI-generated explanations",
        "Historical data comparisons",
        "Model confidence notes and caveats",
      ]),
      p("The Service is not intended to be a perfect forecast of real-world events."),
      h("3. Not Betting, Gambling, or Financial Advice"),
      p("The predictions, probabilities, simulations, rankings, and analysis provided by the Service are **not betting odds**, **not gambling advice**, and **not a recommendation to place any wager**."),
      p(`${COMPANY} does not:`),
      ul([
        "Operate a sportsbook",
        "Accept bets",
        "Facilitate gambling",
        "Provide betting accounts",
        "Recommend wagers",
        "Guarantee betting outcomes",
        "Encourage users to gamble",
      ]),
      p("Any decision you make based on the Service is your own responsibility."),
      p("You should not rely on the Service for gambling, betting, financial, investment, or high-risk decision-making. If you choose to use any information from the Service outside its intended informational and entertainment purpose, you do so entirely at your own risk."),
      h("4. No Guarantee of Accuracy"),
      p("The Service uses data, models, simulations, assumptions, and AI-generated analysis. While we aim to provide useful and thoughtful predictions, we do not guarantee that any prediction, probability, simulation, ranking, analysis, or output will be accurate, complete, current, or reliable."),
      p("Football matches are uncertain. Real-world outcomes may be affected by many factors, including injuries, suspensions, tactics, weather, referee decisions, player form, coaching decisions, data errors, late roster changes, and unpredictable events."),
      p("Predictions may be wrong."),
      p("Data may be incomplete, delayed, outdated, misclassified, or inaccurate."),
      p("AI-generated explanations may contain errors, omissions, or unclear reasoning."),
      p("You are responsible for evaluating the information before relying on it."),
      h("5. Third-Party Data and Sources"),
      p("The Service may rely on third-party data sources, public information, APIs, football statistics providers, official tournament information, historical datasets, team and player data, and other external sources."),
      p("We do not control third-party data sources and are not responsible for their:"),
      ul([
        "Accuracy",
        "Completeness",
        "Availability",
        "Timeliness",
        "Formatting",
        "Licensing changes",
        "Service interruptions",
        "Errors or omissions",
      ]),
      p("Third-party data providers may change, limit, remove, delay, or correct data at any time."),
      p("References to teams, players, matches, tournaments, stadiums, leagues, federations, or organizations are for informational purposes only."),
      h("6. No Affiliation With FIFA or Teams"),
      p(`Unless expressly stated otherwise, ${COMPANY} is not affiliated with, endorsed by, sponsored by, approved by, or officially connected with FIFA, the FIFA World Cup, national football federations, football clubs, players, stadium operators, broadcasters, ticketing platforms, or tournament organizers.`),
      p("Team names, player names, tournament names, match information, logos, statistics, and related references may belong to their respective owners."),
      p("Any use of such references is for informational, descriptive, analytical, and editorial purposes only."),
      h("7. Intellectual Property"),
      p(`The Service, including its original design, interface, prediction logic, model outputs, written content, explanations, graphics, charts, code, structure, branding, and original analysis, is owned by ${COMPANY} or its licensors and is protected by applicable intellectual property laws.`),
      p("You may use the Service for personal, non-commercial informational purposes unless we provide written permission for another use."),
      p("You may not:"),
      ul([
        "Copy, reproduce, or republish substantial parts of the Service",
        "Scrape, extract, or harvest data from the Service",
        "Reverse engineer or attempt to copy the model logic",
        "Use the Service to build a competing prediction product",
        "Remove copyright, attribution, or ownership notices",
        `Misrepresent ${COMPANY} content as your own`,
        "Use our brand, logo, or name without permission",
      ]),
      p(`Limited sharing of small excerpts, screenshots, or links for commentary, discussion, or social media is allowed as long as it is fair, non-misleading, and clearly attributes ${COMPANY}.`),
      h("8. Acceptable Use"),
      p("You agree not to misuse the Service."),
      p("You must not:"),
      ul([
        "Use the Service for unlawful purposes",
        "Attempt to hack, disrupt, overload, or damage the Service",
        "Use bots, scrapers, or automated tools without permission",
        "Interfere with other users' access",
        "Upload malicious code or harmful content",
        "Misrepresent the Service as official FIFA, team, betting, or sportsbook content",
        "Use the Service to promote illegal gambling or unlawful activity",
        "Use the Service in a way that violates applicable laws or third-party rights",
      ]),
      p("We may restrict or terminate access if we believe the Service is being misused."),
      h("9. AI-Generated Content"),
      p("Some parts of the Service may be generated or assisted by artificial intelligence."),
      p("AI-generated content may be useful but can also be incomplete, outdated, incorrect, or unclear. AI outputs should not be treated as professional advice, official tournament information, or guaranteed truth."),
      p("We may update, revise, remove, or correct AI-generated content at any time."),
      h("10. Availability and Changes to the Service"),
      p("We may update, modify, suspend, or discontinue any part of the Service at any time without notice."),
      p("We do not guarantee that the Service will always be available, uninterrupted, secure, or error-free."),
      p("We may change:"),
      ul([
        "Prediction models",
        "Data sources",
        "Features",
        "Analysis methods",
        "User interface",
        "Content",
        "Access rules",
        "Pricing, if applicable in the future",
      ]),
      p("Past predictions may not reflect current model logic after updates."),
      h("11. No Professional Advice"),
      p("The Service does not provide legal, financial, betting, investment, tax, professional sports advisory, or other regulated advice."),
      p("The Service is intended only as general informational and entertainment content."),
      p("You should seek qualified professional advice before making decisions that require professional judgment."),
      h("12. Disclaimer of Warranties"),
      p('The Service is provided on an **"as is"** and **"as available"** basis.'),
      p(`${COMPANY} disclaims all warranties, representations, and conditions to the fullest extent permitted by law, whether express, implied, statutory, or otherwise, including but not limited to warranties of accuracy, completeness, reliability, merchantability, fitness for a particular purpose, non-infringement, availability, and security.`),
      p("We do not warrant that:"),
      ul([
        "The Service will meet your expectations",
        "Predictions will be accurate",
        "Data will be complete or current",
        "The Service will be uninterrupted or error-free",
        "Any defects will be corrected",
        "The Service will be free from harmful components",
      ]),
      h("13. Limitation of Liability"),
      p(`To the fullest extent permitted by applicable law, ${COMPANY} and its owners, employees, contractors, partners, suppliers, and affiliates will not be liable for any direct, indirect, incidental, consequential, special, punitive, exemplary, or other damages arising from or related to your use of, or inability to use, the Service.`),
      p("This includes, without limitation, damages related to:"),
      ul([
        "Incorrect predictions",
        "Data errors or delays",
        "AI-generated errors",
        "Lost profits",
        "Lost opportunities",
        "Betting or gambling losses",
        "Business losses",
        "Service interruptions",
        "Third-party data failures",
        "Unauthorized access or security incidents",
        "Reliance on any content, probability, model output, or analysis",
      ]),
      p("Your use of the Service is at your own risk."),
      p("Some jurisdictions do not allow certain limitations of liability, so some of the above limitations may not apply to you."),
      h("14. Indemnity"),
      p(`You agree to defend, indemnify, and hold harmless ${COMPANY} and its owners, employees, contractors, partners, suppliers, and affiliates from and against any claims, damages, liabilities, losses, costs, or expenses arising from:`),
      ul([
        "Your use or misuse of the Service",
        "Your violation of these Terms",
        "Your violation of applicable laws",
        "Your violation of third-party rights",
        "Any decision you make based on the Service",
      ]),
      h("15. User Feedback"),
      p("If you send us suggestions, comments, corrections, ideas, or feedback about the Service, you agree that we may use them without restriction or compensation to you."),
      p("We appreciate feedback, but we are not obligated to implement any suggestion."),
      h("16. Privacy"),
      p("Your use of the Service is also governed by our Privacy Policy."),
      p("Please review the Privacy Policy to understand how we collect, use, and protect information."),
      h("17. Age Requirement"),
      p("The Service is not directed at children under 13."),
      p("By using the Service, you confirm that you are at least 13 years old or that you are using the Service with permission from a parent or legal guardian where required by law."),
      h("18. Termination"),
      p(`We may suspend, restrict, or terminate your access to the Service at any time if we believe you have violated these Terms, misused the Service, or created risk for ${COMPANY}, other users, or third parties.`),
      h("19. Changes to These Terms"),
      p("We may update these Terms from time to time."),
      p("When we update the Terms, we will change the Last updated date at the top of this page."),
      p("Your continued use of the Service after changes are posted means you accept the updated Terms."),
      h("20. Governing Law"),
      p("These Terms are intended to be governed by the laws of the Province of British Columbia and the federal laws of Canada applicable in British Columbia, unless a qualified legal professional advises otherwise."),
      p("Any disputes related to these Terms or the Service should be handled in the courts or legal forums of British Columbia, Canada, unless applicable law requires otherwise."),
      h("21. Contact"),
      p(`For questions about these Terms, contact **${COMPANY}** in Vancouver, British Columbia, Canada at [${CONTACT_EMAIL}](mailto:${CONTACT_EMAIL}) or visit [${COMPANY_URL.replace(/^https?:\/\//, "")}](${COMPANY_URL}).`),
    ],
  },
};
