-- Migration: enable Row Level Security with a conservative default-deny posture
-- Generated by Phase 0 (RLS posture) of the player-data-resolution execution.
--
-- STATUS: NOT YET EXECUTED. This file is produced for dry-run review at the Phase 0
-- checkpoint. Execution requires explicit "execute RLS migration" approval from Adi.
--
-- Effect: enables RLS on all 41 public tables. No policies are created, so the default
-- is DENY for the `anon` and `authenticated` roles. The `service_role` (BYPASSRLS) and
-- the table owner `postgres` (used by the session pooler) continue to have full access,
-- so all existing Codex scripts keep working unchanged (none use the anon key).
--
-- Reversible while empty of policies: `ALTER TABLE ... DISABLE ROW LEVEL SECURITY;` per table.
--
-- Read policies for public-facing tables (teams, players, fixture_metadata, match_predictions,
-- prediction_runs, tournament_simulation_*, team_strength_snapshots, final_squad_verifications,
-- team_elo_history, historical_matches, match_results) are intentionally DEFERRED to a separate
-- workstream when the public app needs them. Until then, every table is service-role-only.

begin;

alter table public.api_football_fixture_events            enable row level security;
alter table public.api_football_fixture_lineups           enable row level security;
alter table public.api_football_fixture_player_stats      enable row level security;
alter table public.api_football_fixture_statistics        enable row level security;
alter table public.api_football_player_identity_map       enable row level security;
alter table public.final_squad_verifications              enable row level security;
alter table public.fixture_metadata                       enable row level security;
alter table public.fixtures                               enable row level security;
alter table public.historical_match_exclusions            enable row level security;
alter table public.historical_match_import_batches        enable row level security;
alter table public.historical_matches                     enable row level security;
alter table public.historical_matches_martj_staging       enable row level security;
alter table public.historical_team_match_features         enable row level security;
alter table public.match_predictions                      enable row level security;
alter table public.match_results                          enable row level security;
alter table public.model_backtest_results                 enable row level security;
alter table public.model_predictions_backtest             enable row level security;
alter table public.model_training_runs                    enable row level security;
alter table public.national_team_identity_map             enable row level security;
alter table public.national_team_usage_records            enable row level security;
alter table public.player_impact_snapshots                enable row level security;
alter table public.player_metrics                         enable row level security;
alter table public.player_performance_records             enable row level security;
alter table public.player_status_events                   enable row level security;
alter table public.players                                enable row level security;
alter table public.prediction_evaluations                 enable row level security;
alter table public.prediction_runs                        enable row level security;
alter table public.recent_matches                         enable row level security;
alter table public.source_events                          enable row level security;
alter table public.squad_players                          enable row level security;
alter table public.squads                                 enable row level security;
alter table public.team_elo_history                       enable row level security;
alter table public.team_rating_snapshots                  enable row level security;
alter table public.team_ratings                           enable row level security;
alter table public.team_strength_snapshots                enable row level security;
alter table public.team_tactical_snapshots                enable row level security;
alter table public.teams                                  enable row level security;
alter table public.tournament_simulation_fixture_scorelines enable row level security;
alter table public.tournament_simulation_runs             enable row level security;
alter table public.tournament_simulation_team_results     enable row level security;
alter table public.training_match_examples                enable row level security;

commit;

-- Rollback (if needed before any read policies are added):
-- begin;
--   alter table public.api_football_fixture_events disable row level security;
--   ... (repeat per table) ...
-- commit;
